services:
  - type: web
    name: mednet
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        value: base64:uzzF3rzQlFnJKHPFAlV7y7w8pN8JYngzFcpaqAvHmwY=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://mednet-gyfn.onrender.com
      - key: ASSET_URL
        value: https://mednet-gyfn.onrender.com
      - key: FORCE_HTTPS
        value: true
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: sqlite
      - key: FILESYSTEM_DISK
        value: local
